name: Publish Docker
on:
  push:
    branches:
      - java_11
      - java_15

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@master

    - 
      name: Extract branch name
      shell: bash
      #run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch

    - 
      name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - 
      name: docker build
      run: docker build . --tag "ghcr.io/stroeer/java-with-grpc:15" --tag "ghcr.io/stroeer/java-with-grpc:$GITHUB_SHA"
    
    - 
      name: docker push
      run: docker push "ghcr.io/stroeer/amazoncorretto-alpine-grpc:15"